### ISSUE TITLE
JWM 2.4.0 crash at startup with floating point exception

### ISSUE THREAD

**Issue by mdoege** [joewing/jwm#537]
JWM 2.4.0 immediately crashes back to the console for me with startx. Also see this Arch bug report: https://bugs.archlinux.org/task/73049

The crash occurs in DrawButton. Might be a division by zero if height==0: https://github.com/joewing/jwm/blob/master/src/button.c#L148

JWM 2.3.7 works fine for me...

```
(gdb) bt 10
#0  0x00005638e59cca95 in DrawButton (bp=0x7ffcd80d8bf0) at button.c:148
#1  0x00005638e59f2d23 in Draw (cp=0x5638e705e848) at traybutton.c:294
#2  0x00005638e59f18af in StartupTray () at tray.c:145
#3  0x00005638e59c83a3 in Startup () at main.c:526
#4  main (argc=1, argv=<optimized out>) at main.c:191
```
Full crash dump:
```

           PID: 409419 (jwm)
        Signal: 8 (FPE)
     Timestamp: Fri 2021-12-17 13:32:39 CET (1min 11s ago)
  Command Line: jwm
    Executable: /usr/bin/jwm
 Control Group: /user.slice/user-1000.slice/session-17.scope
          Unit: session-17.scope
         Slice: user-1000.slice
       Session: 17
     Disk Size: 779.5K
       Message: Process 409419 (jwm) of user 1000 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 980acba0dcf14f87ddb76843985ce6057470bd1c
                Found module libgvfscommon.so with build-id: 90d1858292300e4e1ee3fbe84ab06079af840ec6
                Found module libgvfsdbus.so with build-id: dcb9d652f2e5c65154517fe6934215ec6bd1c29c
                Found module libXfixes.so.3 with build-id: 0a05c7e8714522bfbdd7c0027c3e2a94965664b0
                Found module libXcursor.so.1 with build-id: eb6315bcd7526aaf51b0a1307efdc587cea0a152
                Found module libuuid.so.1 with build-id: 832a09e0d9568cc6dbe699472218ea2f79dc0f34
                Found module libbrotlicommon.so.1 with build-id: a4ba3f4b4571c8272343b621da812a6e24a202a7
                Found module libstdc++.so.6 with build-id: 9b5eeeb149bf3c4efe787fb398b44f00507aec87
                Found module libicudata.so.70 with build-id: e1dcc2a88cfaafed882d09c90c668af0eed4efed
                Found module librt.so.1 with build-id: 75484da2d6f1515189eefa076e0a40328834cd16
                Found module libblkid.so.1 with build-id: f03a24e92c9852272bd0049b5bcb7ed6cf0e664f
                Found module libzstd.so.1 with build-id: 4b10444c1560ebc574af4d5f488b7408b22d450e
                Found module libICE.so.6 with build-id: af53458a64fe1e62a4d95606f7b03c210b2b098c
                Found module libSM.so.6 with build-id: ac7b055fd3f16b4f29373285ab04ed52eebb632d
                Found module libdatrie.so.1 with build-id: 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                Found module libgraphite2.so.3 with build-id: 47761dc11e553f519cde97ed9ee985be12ccdae2
                Found module libbrotlidec.so.1 with build-id: 45defc036e918e0140a72f1fbce6e7692d38241d
                Found module libbz2.so.1.0 with build-id: 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                Found module libexpat.so.1 with build-id: 8850138eae6d9d4d43c5c4b2ac48393bc4279037
                Found module liblzma.so.5 with build-id: 8b615460aa230708c5183f16bede67aa0437d95e
                Found module libicuuc.so.70 with build-id: 2e245c2bf12f95fd8ab79b3a4be99524677cbd70
                Found module libresolv.so.2 with build-id: c915c72668282861a813f7ea3c0780f37b681dc0
                Found module libmount.so.1 with build-id: ff9a1d99d35cf640d0bfdaba294854372672c29b
                Found module libtiff.so.5 with build-id: e8d89a0fb0847641ddb75c5f03fa89d68155a75d
                Found module libgmodule-2.0.so.0 with build-id: 34cabbd12d9baf397a0255f174e4c96165bc329b
                Found module libXdmcp.so.6 with build-id: 8ca0792d23c8b8b4c0864297512349292bea5955
                Found module libXau.so.6 with build-id: 1c67764663e07bec24d8951e5fd93f4d165979ff
                Found module libXt.so.6 with build-id: c4806824af11e75838db4101f35e67e8284eaaf3
                Found module libthai.so.0 with build-id: 3fdce1a7db2b94d9168eea540dbf5ff5caa3b8ad
                Found module libfribidi.so.0 with build-id: 79124bad061c2aab4ec89f25d067363d5b781114
                Found module libharfbuzz.so.0 with build-id: 1d9dee49dd99162c3f83eb3259c3c88c6b4cd7fe
                Found module libpixman-1.so.0 with build-id: 341f793dcada3a48a306a793d265a517e3f2e7d6
                Found module libxcb-shm.so.0 with build-id: fb797f299a446f559a95afcc168227482cc800d1
                Found module libxcb-render.so.0 with build-id: a37bdb37744b508be9dd29fd9ccb9bb0170d43e5
                Found module libfreetype.so.6 with build-id: 26c5f833068ff72660d1975cbc2074c3eb47fad8
                Found module libfontconfig.so.1 with build-id: 1103a641395c7d3b42e49b793d3a9ea927c77bf6
                Found module libpthread.so.0 with build-id: 07c8f95b4f3251d08550217ad8a1f31066229996
                Found module libpcre.so.1 with build-id: 845483dd0acba86de9f0313102bebbaf3ce52767
                Found module libffi.so.8 with build-id: f90d8b734f6de9b25faedb8cbfab7054dafc0a42
                Found module ld-linux-x86-64.so.2 with build-id: 040cc3dd10461562f177df39e3be2f3704258c3c
                Found module libgcc_s.so.1 with build-id: 7f8508bb914546ada778809b64b99d234337d835
                Found module libpangocairo-1.0.so.0 with build-id: 820de243a3ad1d1d9e12ebc2b6073b19d620d744
                Found module libxml2.so.2 with build-id: 6e67981c9b7528a3502824bf183423a0a02e1075
                Found module libgio-2.0.so.0 with build-id: fc7ccd9c7c26cbb1e938b1c0879f078c2f47d803
                Found module libgdk_pixbuf-2.0.so.0 with build-id: ca4beb15a30de8d8767f7bca8222038c61b58b36
                Found module libcairo-gobject.so.2 with build-id: abbf5a8a182ea1b8b7d68540df5c2e25c0bdae0c
                Found module libm.so.6 with build-id: 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                Found module libz.so.1 with build-id: 81bf6e728a6d6f5b105b0f8b25f6c614ce10452a
                Found module libdl.so.2 with build-id: 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                Found module libxcb.so.1 with build-id: 0d1ef11740a5daad2ee331e812a51aa6574af222
                Found module libc.so.6 with build-id: 4b406737057708c0e4c642345a703c47a61c73dc
                Found module libXinerama.so.1 with build-id: dbb6adece34ea2766d3efcd628af8f9757344dd6
                Found module libXmu.so.6 with build-id: cabffb2fe6d67ed4f260317ca2738ad2a5d3fe85
                Found module libXext.so.6 with build-id: d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                Found module libXpm.so.4 with build-id: 069e7dac32459567d3e9a6d852ec904c399558e1
                Found module libpango-1.0.so.0 with build-id: 5229ea1aff3e7b71fa0f5cceb94cc006311af996
                Found module libpangoft2-1.0.so.0 with build-id: dd01b945fe2134068e5991a7aae05d33ea6b964d
                Found module libpangoxft-1.0.so.0 with build-id: 43e255b0431339d12e0948072cf694517ad97a4b
                Found module libXrender.so.1 with build-id: 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                Found module libXft.so.2 with build-id: 21aed1dfa73fa7301e280e3a573cc2523a1f7ff2
                Found module libjpeg.so.8 with build-id: 879ca18a2f58c25d77ba881db3a44a5676ef6c7d
                Found module libcairo.so.2 with build-id: 06820af9cf79c2deb207d9533a61caf04e67a8ad
                Found module libglib-2.0.so.0 with build-id: 8214b56e554b7cbead4034b6ba32c90bc8c674da
                Found module libgobject-2.0.so.0 with build-id: 3e451709a0a5772b9550d3a4c28dcb37a87028fa
                Found module librsvg-2.so.2 with build-id: 386351f79d7a10d84fa858631fc4b92d1cbd24f2
                Found module libpng16.so.16 with build-id: 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                Found module libX11.so.6 with build-id: 5ba5798d193c0065014b8c6252a0678671c8d478
                Found module jwm with build-id: 92728edc96400606239cd0c1456ac26bf41bc010
                Stack trace of thread 409419:
                #0  0x00005638e59cca95 DrawButton (jwm + 0xca95)
                #1  0x00005638e59f2d23 Draw (jwm + 0x32d23)
                #2  0x00005638e59f18af StartupTray (jwm + 0x318af)
                #3  0x00005638e59c83a3 Startup (jwm + 0x83a3)
                #4  0x00007fa4a45c4b25 __libc_start_main (libc.so.6 + 0x27b25)
                #5  0x00005638e59c85ee _start (jwm + 0x85ee)
                
                Stack trace of thread 409430:
                #0  0x00007fa4a4690b2f __poll (libc.so.6 + 0xf3b2f)
                #1  0x00007fa4a4abd749 n/a (libglib-2.0.so.0 + 0xa8749)
                #2  0x00007fa4a4a66c11 g_main_context_iteration (libglib-2.0.so.0 + 0x51c11)
                #3  0x00007fa4a4a66c62 n/a (libglib-2.0.so.0 + 0x51c62)
                #4  0x00007fa4a4a97d51 n/a (libglib-2.0.so.0 + 0x82d51)
                #5  0x00007fa4a3fc3259 start_thread (libpthread.so.0 + 0x9259)
                #6  0x00007fa4a469b5e3 __clone (libc.so.6 + 0xfe5e3)
                
                Stack trace of thread 409431:
                #0  0x00007fa4a4690b2f __poll (libc.so.6 + 0xf3b2f)
                #1  0x00007fa4a4abd749 n/a (libglib-2.0.so.0 + 0xa8749)
                #2  0x00007fa4a4a68ab3 g_main_loop_run (libglib-2.0.so.0 + 0x53ab3)
                #3  0x00007fa4a42fd598 n/a (libgio-2.0.so.0 + 0x103598)
                #4  0x00007fa4a4a97d51 n/a (libglib-2.0.so.0 + 0x82d51)
                #5  0x00007fa4a3fc3259 start_thread (libpthread.so.0 + 0x9259)
                #6  0x00007fa4a469b5e3 __clone (libc.so.6 + 0xfe5e3)

```

**Comment by mdoege** [comment]
P.S. The culprit seems to be the jwm-blue.svg icon.

If I replace

```<TrayButton icon="jwm-blue">root:1</TrayButton>```

with

```<TrayButton label="J">root:1</TrayButton>```

then JWM 2.4.0 starts successfully.

**Comment by joewing** [comment]
Thanks for reporting this! I think the root of the problem has to do with the the way JWM was using the new API for rsvg. This should be fixed in master and in the next release.

**Comment by mdoege** [comment]
Great, thanks!

I have also noticed a line of corrupted pixels at the bottom of the screen with 2.4.0 when returning from fullscreen, e.g. after watching a YouTube video. This does not happen with 2.3.x.

It's not important enough to start a separate GitHub issue about I think, but it does look a bit ugly and buggy, so if you have any ideas what could cause this...

**Comment by jmandawg** [comment]
Same issue on archlinux, thanks for fixing.

**Comment by mdoege** [comment]
@jmandawg This whole thread is about Arch Linux...
